dataset:
  data_directory: "/workspace/data/TOSSIT_sims"
  exp_data_directory: "/workspace/data/cape_cod_bay/acoustics"
  entry_keys: [T, data, fs, labels, t_dec_max, t_dec_min, class_labels]
signal:
  fs: 600 # [Hz]
  T: 6 # [s]
stft:
  window: "hann"
  nperseg: 62
  noverlap: 56
  nfft: 463
scaling:
  max_x: 8964.86 # [m]
  min_x: -12206.00 # [m]
  max_y: 10563.48 # [m]
  min_y: -3984.47 # [m]
models:
  checkpoints_directories: "/workspace/data/models"