dataset:
  data_directory: "/workspace/data/TOSSIT_sims"
  exp_data_directory: "/workspace/data/cape_cod_bay/acoustics"
  entry_keys: [T, data, fs, labels, t_dec_max, t_dec_min, class_labels]
signal:
  fs: 600 # [Hz]
  T: 6 # [s]
stft:
  window: "hann"
  nperseg: 62
  noverlap: 40
  nfft: 463
scaling:
  max_x: 10226.245406
  min_x: -10986.304187
  max_y: 20941.644405
  min_y: -7598.295757
models:
  checkpoints_directories: "/workspace/data/models"