% path to rsk file
rskFileDeploy = '/media/markgoldwater/Extreme SSD/CCB_2023/deployment_metadata/203246_20230404_1741.rsk';
rskFileRecover = '/media/markgoldwater/Extreme SSD/CCB_2023/recovery_metadata/203246_20230428_1824.rsk';

% extract deployment temperature, salinity, and sound speed profiles
[T_d, S_d, c_d, z_d] = EnvCTD2Profiles(rskFileDeploy);

% plot
EnvPlotProfiles(T_d, S_d, c_d, z_d,...
                'title', 'Deployment Profiles',...
                'czRange', [5, 40],...
                'TzRange', [9, 40],...
                'SzRange', [3, 40])

% extract recovery temperature, salinity, and sound speed profiles
[T_r, S_r, c_r, z_r] = EnvCTD2Profiles(rskFileRecover);

% plot
EnvPlotProfiles(T_r, S_r, c_r, z_r,...
                'title', 'Recovery Profiles',...
                'czRange', [5, 40],...
                'TzRange', [9, 40],...
                'SzRange', [3, 40])